name: CI

on:
  schedule:
    - cron: '0 45 18 * * ?'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Create local changes
      run: |
        yarn install
        yarn main
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Track changes" -a
    - name: Push changes
      uses: furstenheim/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
